<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('EstudioSocioeconomico', 'doctrine');

/**
 * BaseEstudioSocioeconomico
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $estudiante_id
 * @property integer $grupo_familiar_id
 * @property integer $profesion_jefe_id
 * @property integer $instruccion_madre_id
 * @property integer $ingreso_familiar_id
 * @property integer $condicion_vivienda_id
 * @property integer $tenencia_vivienda_id
 * @property integer $material_paredes_id
 * @property integer $material_techo_id
 * @property integer $material_piso_id
 * @property integer $numero_ambientes_id
 * @property boolean $electricidad
 * @property boolean $agua
 * @property boolean $red_de_cloacas
 * @property boolean $telefono_fijo_linea
 * @property boolean $telefono_fijo_enchufe
 * @property boolean $gas_directo
 * @property boolean $gas_bombona
 * @property boolean $aseo_urbano
 * @property boolean $internet
 * @property boolean $tv
 * @property boolean $mental_intelectual
 * @property boolean $mental_psicosocial
 * @property boolean $visual
 * @property boolean $auditiva
 * @property boolean $voz_y_habla
 * @property boolean $cardiovascular
 * @property boolean $respiratoria
 * @property boolean $metabolica
 * @property boolean $neurologica
 * @property boolean $musculo_esqueletico
 * @property boolean $sensitiva
 * @property boolean $genitourinaria
 * @property string $otra_discapacidad
 * @property CondicionVivienda $CondicionVivienda
 * @property Estudiante $Estudiante
 * @property GrupoFamiliar $GrupoFamiliar
 * @property IngresoFamiliar $IngresoFamiliar
 * @property InstruccionMadre $InstruccionMadre
 * @property MaterialParedes $MaterialParedes
 * @property MaterialPiso $MaterialPiso
 * @property MaterialTecho $MaterialTecho
 * @property NumeroAmbientes $NumeroAmbientes
 * @property ProfesionJefe $ProfesionJefe
 * @property TenenciaVivienda $TenenciaVivienda
 * 
 * @method integer               getId()                    Returns the current record's "id" value
 * @method integer               getEstudianteId()          Returns the current record's "estudiante_id" value
 * @method integer               getGrupoFamiliarId()       Returns the current record's "grupo_familiar_id" value
 * @method integer               getProfesionJefeId()       Returns the current record's "profesion_jefe_id" value
 * @method integer               getInstruccionMadreId()    Returns the current record's "instruccion_madre_id" value
 * @method integer               getIngresoFamiliarId()     Returns the current record's "ingreso_familiar_id" value
 * @method integer               getCondicionViviendaId()   Returns the current record's "condicion_vivienda_id" value
 * @method integer               getTenenciaViviendaId()    Returns the current record's "tenencia_vivienda_id" value
 * @method integer               getMaterialParedesId()     Returns the current record's "material_paredes_id" value
 * @method integer               getMaterialTechoId()       Returns the current record's "material_techo_id" value
 * @method integer               getMaterialPisoId()        Returns the current record's "material_piso_id" value
 * @method integer               getNumeroAmbientesId()     Returns the current record's "numero_ambientes_id" value
 * @method boolean               getElectricidad()          Returns the current record's "electricidad" value
 * @method boolean               getAgua()                  Returns the current record's "agua" value
 * @method boolean               getRedDeCloacas()          Returns the current record's "red_de_cloacas" value
 * @method boolean               getTelefonoFijoLinea()     Returns the current record's "telefono_fijo_linea" value
 * @method boolean               getTelefonoFijoEnchufe()   Returns the current record's "telefono_fijo_enchufe" value
 * @method boolean               getGasDirecto()            Returns the current record's "gas_directo" value
 * @method boolean               getGasBombona()            Returns the current record's "gas_bombona" value
 * @method boolean               getAseoUrbano()            Returns the current record's "aseo_urbano" value
 * @method boolean               getInternet()              Returns the current record's "internet" value
 * @method boolean               getTv()                    Returns the current record's "tv" value
 * @method boolean               getMentalIntelectual()     Returns the current record's "mental_intelectual" value
 * @method boolean               getMentalPsicosocial()     Returns the current record's "mental_psicosocial" value
 * @method boolean               getVisual()                Returns the current record's "visual" value
 * @method boolean               getAuditiva()              Returns the current record's "auditiva" value
 * @method boolean               getVozYHabla()             Returns the current record's "voz_y_habla" value
 * @method boolean               getCardiovascular()        Returns the current record's "cardiovascular" value
 * @method boolean               getRespiratoria()          Returns the current record's "respiratoria" value
 * @method boolean               getMetabolica()            Returns the current record's "metabolica" value
 * @method boolean               getNeurologica()           Returns the current record's "neurologica" value
 * @method boolean               getMusculoEsqueletico()    Returns the current record's "musculo_esqueletico" value
 * @method boolean               getSensitiva()             Returns the current record's "sensitiva" value
 * @method boolean               getGenitourinaria()        Returns the current record's "genitourinaria" value
 * @method string                getOtraDiscapacidad()      Returns the current record's "otra_discapacidad" value
 * @method CondicionVivienda     getCondicionVivienda()     Returns the current record's "CondicionVivienda" value
 * @method Estudiante            getEstudiante()            Returns the current record's "Estudiante" value
 * @method GrupoFamiliar         getGrupoFamiliar()         Returns the current record's "GrupoFamiliar" value
 * @method IngresoFamiliar       getIngresoFamiliar()       Returns the current record's "IngresoFamiliar" value
 * @method InstruccionMadre      getInstruccionMadre()      Returns the current record's "InstruccionMadre" value
 * @method MaterialParedes       getMaterialParedes()       Returns the current record's "MaterialParedes" value
 * @method MaterialPiso          getMaterialPiso()          Returns the current record's "MaterialPiso" value
 * @method MaterialTecho         getMaterialTecho()         Returns the current record's "MaterialTecho" value
 * @method NumeroAmbientes       getNumeroAmbientes()       Returns the current record's "NumeroAmbientes" value
 * @method ProfesionJefe         getProfesionJefe()         Returns the current record's "ProfesionJefe" value
 * @method TenenciaVivienda      getTenenciaVivienda()      Returns the current record's "TenenciaVivienda" value
 * @method EstudioSocioeconomico setId()                    Sets the current record's "id" value
 * @method EstudioSocioeconomico setEstudianteId()          Sets the current record's "estudiante_id" value
 * @method EstudioSocioeconomico setGrupoFamiliarId()       Sets the current record's "grupo_familiar_id" value
 * @method EstudioSocioeconomico setProfesionJefeId()       Sets the current record's "profesion_jefe_id" value
 * @method EstudioSocioeconomico setInstruccionMadreId()    Sets the current record's "instruccion_madre_id" value
 * @method EstudioSocioeconomico setIngresoFamiliarId()     Sets the current record's "ingreso_familiar_id" value
 * @method EstudioSocioeconomico setCondicionViviendaId()   Sets the current record's "condicion_vivienda_id" value
 * @method EstudioSocioeconomico setTenenciaViviendaId()    Sets the current record's "tenencia_vivienda_id" value
 * @method EstudioSocioeconomico setMaterialParedesId()     Sets the current record's "material_paredes_id" value
 * @method EstudioSocioeconomico setMaterialTechoId()       Sets the current record's "material_techo_id" value
 * @method EstudioSocioeconomico setMaterialPisoId()        Sets the current record's "material_piso_id" value
 * @method EstudioSocioeconomico setNumeroAmbientesId()     Sets the current record's "numero_ambientes_id" value
 * @method EstudioSocioeconomico setElectricidad()          Sets the current record's "electricidad" value
 * @method EstudioSocioeconomico setAgua()                  Sets the current record's "agua" value
 * @method EstudioSocioeconomico setRedDeCloacas()          Sets the current record's "red_de_cloacas" value
 * @method EstudioSocioeconomico setTelefonoFijoLinea()     Sets the current record's "telefono_fijo_linea" value
 * @method EstudioSocioeconomico setTelefonoFijoEnchufe()   Sets the current record's "telefono_fijo_enchufe" value
 * @method EstudioSocioeconomico setGasDirecto()            Sets the current record's "gas_directo" value
 * @method EstudioSocioeconomico setGasBombona()            Sets the current record's "gas_bombona" value
 * @method EstudioSocioeconomico setAseoUrbano()            Sets the current record's "aseo_urbano" value
 * @method EstudioSocioeconomico setInternet()              Sets the current record's "internet" value
 * @method EstudioSocioeconomico setTv()                    Sets the current record's "tv" value
 * @method EstudioSocioeconomico setMentalIntelectual()     Sets the current record's "mental_intelectual" value
 * @method EstudioSocioeconomico setMentalPsicosocial()     Sets the current record's "mental_psicosocial" value
 * @method EstudioSocioeconomico setVisual()                Sets the current record's "visual" value
 * @method EstudioSocioeconomico setAuditiva()              Sets the current record's "auditiva" value
 * @method EstudioSocioeconomico setVozYHabla()             Sets the current record's "voz_y_habla" value
 * @method EstudioSocioeconomico setCardiovascular()        Sets the current record's "cardiovascular" value
 * @method EstudioSocioeconomico setRespiratoria()          Sets the current record's "respiratoria" value
 * @method EstudioSocioeconomico setMetabolica()            Sets the current record's "metabolica" value
 * @method EstudioSocioeconomico setNeurologica()           Sets the current record's "neurologica" value
 * @method EstudioSocioeconomico setMusculoEsqueletico()    Sets the current record's "musculo_esqueletico" value
 * @method EstudioSocioeconomico setSensitiva()             Sets the current record's "sensitiva" value
 * @method EstudioSocioeconomico setGenitourinaria()        Sets the current record's "genitourinaria" value
 * @method EstudioSocioeconomico setOtraDiscapacidad()      Sets the current record's "otra_discapacidad" value
 * @method EstudioSocioeconomico setCondicionVivienda()     Sets the current record's "CondicionVivienda" value
 * @method EstudioSocioeconomico setEstudiante()            Sets the current record's "Estudiante" value
 * @method EstudioSocioeconomico setGrupoFamiliar()         Sets the current record's "GrupoFamiliar" value
 * @method EstudioSocioeconomico setIngresoFamiliar()       Sets the current record's "IngresoFamiliar" value
 * @method EstudioSocioeconomico setInstruccionMadre()      Sets the current record's "InstruccionMadre" value
 * @method EstudioSocioeconomico setMaterialParedes()       Sets the current record's "MaterialParedes" value
 * @method EstudioSocioeconomico setMaterialPiso()          Sets the current record's "MaterialPiso" value
 * @method EstudioSocioeconomico setMaterialTecho()         Sets the current record's "MaterialTecho" value
 * @method EstudioSocioeconomico setNumeroAmbientes()       Sets the current record's "NumeroAmbientes" value
 * @method EstudioSocioeconomico setProfesionJefe()         Sets the current record's "ProfesionJefe" value
 * @method EstudioSocioeconomico setTenenciaVivienda()      Sets the current record's "TenenciaVivienda" value
 * 
 * @package    ucs_control
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEstudioSocioeconomico extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('estudio_socioeconomico');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'estudio_socioeconomico_id',
             'length' => 4,
             ));
        $this->hasColumn('estudiante_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('grupo_familiar_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('profesion_jefe_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('instruccion_madre_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('ingreso_familiar_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('condicion_vivienda_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('tenencia_vivienda_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('material_paredes_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('material_techo_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('material_piso_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('numero_ambientes_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('electricidad', 'boolean', 1, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('agua', 'boolean', 1, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('red_de_cloacas', 'boolean', 1, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('telefono_fijo_linea', 'boolean', 1, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('telefono_fijo_enchufe', 'boolean', 1, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('gas_directo', 'boolean', 1, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('gas_bombona', 'boolean', 1, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('aseo_urbano', 'boolean', 1, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('internet', 'boolean', 1, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('tv', 'boolean', 1, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('mental_intelectual', 'boolean', 1, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('mental_psicosocial', 'boolean', 1, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('visual', 'boolean', 1, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('auditiva', 'boolean', 1, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('voz_y_habla', 'boolean', 1, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('cardiovascular', 'boolean', 1, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('respiratoria', 'boolean', 1, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('metabolica', 'boolean', 1, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('neurologica', 'boolean', 1, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('musculo_esqueletico', 'boolean', 1, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('sensitiva', 'boolean', 1, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('genitourinaria', 'boolean', 1, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('otra_discapacidad', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('CondicionVivienda', array(
             'local' => 'condicion_vivienda_id',
             'foreign' => 'id'));

        $this->hasOne('Estudiante', array(
             'local' => 'estudiante_id',
             'foreign' => 'id'));

        $this->hasOne('GrupoFamiliar', array(
             'local' => 'grupo_familiar_id',
             'foreign' => 'id'));

        $this->hasOne('IngresoFamiliar', array(
             'local' => 'ingreso_familiar_id',
             'foreign' => 'id'));

        $this->hasOne('InstruccionMadre', array(
             'local' => 'instruccion_madre_id',
             'foreign' => 'id'));

        $this->hasOne('MaterialParedes', array(
             'local' => 'material_paredes_id',
             'foreign' => 'id'));

        $this->hasOne('MaterialPiso', array(
             'local' => 'material_piso_id',
             'foreign' => 'id'));

        $this->hasOne('MaterialTecho', array(
             'local' => 'material_techo_id',
             'foreign' => 'id'));

        $this->hasOne('NumeroAmbientes', array(
             'local' => 'numero_ambientes_id',
             'foreign' => 'id'));

        $this->hasOne('ProfesionJefe', array(
             'local' => 'profesion_jefe_id',
             'foreign' => 'id'));

        $this->hasOne('TenenciaVivienda', array(
             'local' => 'tenencia_vivienda_id',
             'foreign' => 'id'));
    }
}