<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Parroquia', 'doctrine');

/**
 * BaseParroquia
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $descripcion
 * @property integer $municipio_id
 * @property integer $estado_codigo
 * @property integer $municipio_codigo
 * @property integer $parroquia_codigo
 * @property Doctrine_Collection $Estudiante
 * 
 * @method integer             getId()               Returns the current record's "id" value
 * @method string              getDescripcion()      Returns the current record's "descripcion" value
 * @method integer             getMunicipioId()      Returns the current record's "municipio_id" value
 * @method integer             getEstadoCodigo()     Returns the current record's "estado_codigo" value
 * @method integer             getMunicipioCodigo()  Returns the current record's "municipio_codigo" value
 * @method integer             getParroquiaCodigo()  Returns the current record's "parroquia_codigo" value
 * @method Doctrine_Collection getEstudiante()       Returns the current record's "Estudiante" collection
 * @method Parroquia           setId()               Sets the current record's "id" value
 * @method Parroquia           setDescripcion()      Sets the current record's "descripcion" value
 * @method Parroquia           setMunicipioId()      Sets the current record's "municipio_id" value
 * @method Parroquia           setEstadoCodigo()     Sets the current record's "estado_codigo" value
 * @method Parroquia           setMunicipioCodigo()  Sets the current record's "municipio_codigo" value
 * @method Parroquia           setParroquiaCodigo()  Sets the current record's "parroquia_codigo" value
 * @method Parroquia           setEstudiante()       Sets the current record's "Estudiante" collection
 * 
 * @package    ucs_control
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseParroquia extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('parroquia');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'parroquia_id',
             'length' => 4,
             ));
        $this->hasColumn('descripcion', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('municipio_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('estado_codigo', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('municipio_codigo', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('parroquia_codigo', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Estudiante', array(
             'local' => 'id',
             'foreign' => 'parroquia_id'));
    }
}