<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('OtraInformacion', 'doctrine');

/**
 * BaseOtraInformacion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $estudiante_id
 * @property string $base_mision
 * @property string $det_base_mision
 * @property string $org_dep
 * @property string $det_org_deportiva
 * @property string $org_cultural
 * @property string $det_org_cultural
 * @property string $org_ecologista
 * @property string $det_org_ecologista
 * @property string $org_productiva
 * @property string $det_org_productiva
 * @property string $mil_bolivariana
 * @property string $det_mil_bolivariana
 * @property string $iniciativa_productiva
 * @property string $facebook
 * @property string $twitter
 * @property string $instagram
 * @property string $org_politica_estudiantil
 * @property string $det_org_politica_estudiantil
 * @property Estudiante $Estudiante
 * 
 * @method integer         getId()                           Returns the current record's "id" value
 * @method integer         getEstudianteId()                 Returns the current record's "estudiante_id" value
 * @method string          getBaseMision()                   Returns the current record's "base_mision" value
 * @method string          getDetBaseMision()                Returns the current record's "det_base_mision" value
 * @method string          getOrgDep()                       Returns the current record's "org_dep" value
 * @method string          getDetOrgDeportiva()              Returns the current record's "det_org_deportiva" value
 * @method string          getOrgCultural()                  Returns the current record's "org_cultural" value
 * @method string          getDetOrgCultural()               Returns the current record's "det_org_cultural" value
 * @method string          getOrgEcologista()                Returns the current record's "org_ecologista" value
 * @method string          getDetOrgEcologista()             Returns the current record's "det_org_ecologista" value
 * @method string          getOrgProductiva()                Returns the current record's "org_productiva" value
 * @method string          getDetOrgProductiva()             Returns the current record's "det_org_productiva" value
 * @method string          getMilBolivariana()               Returns the current record's "mil_bolivariana" value
 * @method string          getDetMilBolivariana()            Returns the current record's "det_mil_bolivariana" value
 * @method string          getIniciativaProductiva()         Returns the current record's "iniciativa_productiva" value
 * @method string          getFacebook()                     Returns the current record's "facebook" value
 * @method string          getTwitter()                      Returns the current record's "twitter" value
 * @method string          getInstagram()                    Returns the current record's "instagram" value
 * @method string          getOrgPoliticaEstudiantil()       Returns the current record's "org_politica_estudiantil" value
 * @method string          getDetOrgPoliticaEstudiantil()    Returns the current record's "det_org_politica_estudiantil" value
 * @method Estudiante      getEstudiante()                   Returns the current record's "Estudiante" value
 * @method OtraInformacion setId()                           Sets the current record's "id" value
 * @method OtraInformacion setEstudianteId()                 Sets the current record's "estudiante_id" value
 * @method OtraInformacion setBaseMision()                   Sets the current record's "base_mision" value
 * @method OtraInformacion setDetBaseMision()                Sets the current record's "det_base_mision" value
 * @method OtraInformacion setOrgDep()                       Sets the current record's "org_dep" value
 * @method OtraInformacion setDetOrgDeportiva()              Sets the current record's "det_org_deportiva" value
 * @method OtraInformacion setOrgCultural()                  Sets the current record's "org_cultural" value
 * @method OtraInformacion setDetOrgCultural()               Sets the current record's "det_org_cultural" value
 * @method OtraInformacion setOrgEcologista()                Sets the current record's "org_ecologista" value
 * @method OtraInformacion setDetOrgEcologista()             Sets the current record's "det_org_ecologista" value
 * @method OtraInformacion setOrgProductiva()                Sets the current record's "org_productiva" value
 * @method OtraInformacion setDetOrgProductiva()             Sets the current record's "det_org_productiva" value
 * @method OtraInformacion setMilBolivariana()               Sets the current record's "mil_bolivariana" value
 * @method OtraInformacion setDetMilBolivariana()            Sets the current record's "det_mil_bolivariana" value
 * @method OtraInformacion setIniciativaProductiva()         Sets the current record's "iniciativa_productiva" value
 * @method OtraInformacion setFacebook()                     Sets the current record's "facebook" value
 * @method OtraInformacion setTwitter()                      Sets the current record's "twitter" value
 * @method OtraInformacion setInstagram()                    Sets the current record's "instagram" value
 * @method OtraInformacion setOrgPoliticaEstudiantil()       Sets the current record's "org_politica_estudiantil" value
 * @method OtraInformacion setDetOrgPoliticaEstudiantil()    Sets the current record's "det_org_politica_estudiantil" value
 * @method OtraInformacion setEstudiante()                   Sets the current record's "Estudiante" value
 * 
 * @package    ucs_control
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOtraInformacion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('otra_informacion');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'otra_informacion_id',
             'length' => 4,
             ));
        $this->hasColumn('estudiante_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('base_mision', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('det_base_mision', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('org_dep', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('det_org_deportiva', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('org_cultural', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('det_org_cultural', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('org_ecologista', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('det_org_ecologista', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('org_productiva', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('det_org_productiva', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('mil_bolivariana', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('det_mil_bolivariana', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('iniciativa_productiva', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('facebook', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('twitter', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('instagram', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('org_politica_estudiantil', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('det_org_politica_estudiantil', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Estudiante', array(
             'local' => 'estudiante_id',
             'foreign' => 'id'));
    }
}