<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Preinscripcion', 'doctrine');

/**
 * BasePreinscripcion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nacionalidad
 * @property string $identificacion
 * @property string $pnombre
 * @property string $snombre
 * @property string $papellido
 * @property string $sapellido
 * @property string $genero
 * @property date $fnac
 * @property integer $pais_origen_id
 * @property integer $estado_id
 * @property integer $municipio_id
 * @property integer $parroquia_id
 * @property string $direccion
 * @property string $telefono
 * @property string $correo
 * @property string $twitter
 * @property integer $titulo_id
 * @property string $uni_pre
 * @property string $mgi
 * @property string $uni_mgi
 * @property string $otra
 * @property string $uni_otra
 * @property string $art_8
 * @property integer $pnfa_id
 * @property string $otra_especializacion
 * @property string $ano_pre
 * @property string $ano_mgi
 * @property string $ano_otra
 * @property Estado $Estado
 * @property Municipio $Municipio
 * @property PaisOrigen $PaisOrigen
 * @property Parroquia $Parroquia
 * @property Pnfa $Pnfa
 * @property Titulo $Titulo
 * 
 * @method integer        getId()                   Returns the current record's "id" value
 * @method string         getNacionalidad()         Returns the current record's "nacionalidad" value
 * @method string         getIdentificacion()       Returns the current record's "identificacion" value
 * @method string         getPnombre()              Returns the current record's "pnombre" value
 * @method string         getSnombre()              Returns the current record's "snombre" value
 * @method string         getPapellido()            Returns the current record's "papellido" value
 * @method string         getSapellido()            Returns the current record's "sapellido" value
 * @method string         getGenero()               Returns the current record's "genero" value
 * @method date           getFnac()                 Returns the current record's "fnac" value
 * @method integer        getPaisOrigenId()         Returns the current record's "pais_origen_id" value
 * @method integer        getEstadoId()             Returns the current record's "estado_id" value
 * @method integer        getMunicipioId()          Returns the current record's "municipio_id" value
 * @method integer        getParroquiaId()          Returns the current record's "parroquia_id" value
 * @method string         getDireccion()            Returns the current record's "direccion" value
 * @method string         getTelefono()             Returns the current record's "telefono" value
 * @method string         getCorreo()               Returns the current record's "correo" value
 * @method string         getTwitter()              Returns the current record's "twitter" value
 * @method integer        getTituloId()             Returns the current record's "titulo_id" value
 * @method string         getUniPre()               Returns the current record's "uni_pre" value
 * @method string         getMgi()                  Returns the current record's "mgi" value
 * @method string         getUniMgi()               Returns the current record's "uni_mgi" value
 * @method string         getOtra()                 Returns the current record's "otra" value
 * @method string         getUniOtra()              Returns the current record's "uni_otra" value
 * @method string         getArt8()                 Returns the current record's "art_8" value
 * @method integer        getPnfaId()               Returns the current record's "pnfa_id" value
 * @method string         getOtraEspecializacion()  Returns the current record's "otra_especializacion" value
 * @method string         getAnoPre()               Returns the current record's "ano_pre" value
 * @method string         getAnoMgi()               Returns the current record's "ano_mgi" value
 * @method string         getAnoOtra()              Returns the current record's "ano_otra" value
 * @method Estado         getEstado()               Returns the current record's "Estado" value
 * @method Municipio      getMunicipio()            Returns the current record's "Municipio" value
 * @method PaisOrigen     getPaisOrigen()           Returns the current record's "PaisOrigen" value
 * @method Parroquia      getParroquia()            Returns the current record's "Parroquia" value
 * @method Pnfa           getPnfa()                 Returns the current record's "Pnfa" value
 * @method Titulo         getTitulo()               Returns the current record's "Titulo" value
 * @method Preinscripcion setId()                   Sets the current record's "id" value
 * @method Preinscripcion setNacionalidad()         Sets the current record's "nacionalidad" value
 * @method Preinscripcion setIdentificacion()       Sets the current record's "identificacion" value
 * @method Preinscripcion setPnombre()              Sets the current record's "pnombre" value
 * @method Preinscripcion setSnombre()              Sets the current record's "snombre" value
 * @method Preinscripcion setPapellido()            Sets the current record's "papellido" value
 * @method Preinscripcion setSapellido()            Sets the current record's "sapellido" value
 * @method Preinscripcion setGenero()               Sets the current record's "genero" value
 * @method Preinscripcion setFnac()                 Sets the current record's "fnac" value
 * @method Preinscripcion setPaisOrigenId()         Sets the current record's "pais_origen_id" value
 * @method Preinscripcion setEstadoId()             Sets the current record's "estado_id" value
 * @method Preinscripcion setMunicipioId()          Sets the current record's "municipio_id" value
 * @method Preinscripcion setParroquiaId()          Sets the current record's "parroquia_id" value
 * @method Preinscripcion setDireccion()            Sets the current record's "direccion" value
 * @method Preinscripcion setTelefono()             Sets the current record's "telefono" value
 * @method Preinscripcion setCorreo()               Sets the current record's "correo" value
 * @method Preinscripcion setTwitter()              Sets the current record's "twitter" value
 * @method Preinscripcion setTituloId()             Sets the current record's "titulo_id" value
 * @method Preinscripcion setUniPre()               Sets the current record's "uni_pre" value
 * @method Preinscripcion setMgi()                  Sets the current record's "mgi" value
 * @method Preinscripcion setUniMgi()               Sets the current record's "uni_mgi" value
 * @method Preinscripcion setOtra()                 Sets the current record's "otra" value
 * @method Preinscripcion setUniOtra()              Sets the current record's "uni_otra" value
 * @method Preinscripcion setArt8()                 Sets the current record's "art_8" value
 * @method Preinscripcion setPnfaId()               Sets the current record's "pnfa_id" value
 * @method Preinscripcion setOtraEspecializacion()  Sets the current record's "otra_especializacion" value
 * @method Preinscripcion setAnoPre()               Sets the current record's "ano_pre" value
 * @method Preinscripcion setAnoMgi()               Sets the current record's "ano_mgi" value
 * @method Preinscripcion setAnoOtra()              Sets the current record's "ano_otra" value
 * @method Preinscripcion setEstado()               Sets the current record's "Estado" value
 * @method Preinscripcion setMunicipio()            Sets the current record's "Municipio" value
 * @method Preinscripcion setPaisOrigen()           Sets the current record's "PaisOrigen" value
 * @method Preinscripcion setParroquia()            Sets the current record's "Parroquia" value
 * @method Preinscripcion setPnfa()                 Sets the current record's "Pnfa" value
 * @method Preinscripcion setTitulo()               Sets the current record's "Titulo" value
 * 
 * @package    ucs_control
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePreinscripcion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('preinscripcion');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'preinscripcion_id',
             'length' => 4,
             ));
        $this->hasColumn('nacionalidad', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('identificacion', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('pnombre', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('snombre', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('papellido', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('sapellido', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('genero', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('fnac', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 25,
             ));
        $this->hasColumn('pais_origen_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('estado_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('municipio_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('parroquia_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('direccion', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('telefono', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('correo', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('twitter', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('titulo_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('uni_pre', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('mgi', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('uni_mgi', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('otra', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('uni_otra', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('art_8', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('pnfa_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('otra_especializacion', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('ano_pre', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('ano_mgi', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('ano_otra', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Estado', array(
             'local' => 'estado_id',
             'foreign' => 'id'));

        $this->hasOne('Municipio', array(
             'local' => 'municipio_id',
             'foreign' => 'id'));

        $this->hasOne('PaisOrigen', array(
             'local' => 'pais_origen_id',
             'foreign' => 'id'));

        $this->hasOne('Parroquia', array(
             'local' => 'parroquia_id',
             'foreign' => 'id'));

        $this->hasOne('Pnfa', array(
             'local' => 'pnfa_id',
             'foreign' => 'id'));

        $this->hasOne('Titulo', array(
             'local' => 'titulo_id',
             'foreign' => 'id'));
    }
}