<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Reclamo', 'doctrine');

/**
 * BaseReclamo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $tipo_reclamo_id
 * @property string $descripcion
 * @property string $estatus
 * @property integer $estudiante_id
 * @property Estudiante $Estudiante
 * @property TipoReclamo $TipoReclamo
 * 
 * @method integer     getId()              Returns the current record's "id" value
 * @method integer     getTipoReclamoId()   Returns the current record's "tipo_reclamo_id" value
 * @method string      getDescripcion()     Returns the current record's "descripcion" value
 * @method string      getEstatus()         Returns the current record's "estatus" value
 * @method integer     getEstudianteId()    Returns the current record's "estudiante_id" value
 * @method Estudiante  getEstudiante()      Returns the current record's "Estudiante" value
 * @method TipoReclamo getTipoReclamo()     Returns the current record's "TipoReclamo" value
 * @method Reclamo     setId()              Sets the current record's "id" value
 * @method Reclamo     setTipoReclamoId()   Sets the current record's "tipo_reclamo_id" value
 * @method Reclamo     setDescripcion()     Sets the current record's "descripcion" value
 * @method Reclamo     setEstatus()         Sets the current record's "estatus" value
 * @method Reclamo     setEstudianteId()    Sets the current record's "estudiante_id" value
 * @method Reclamo     setEstudiante()      Sets the current record's "Estudiante" value
 * @method Reclamo     setTipoReclamo()     Sets the current record's "TipoReclamo" value
 * 
 * @package    ucs_control
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseReclamo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('reclamo');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'reclamo_id',
             'length' => 4,
             ));
        $this->hasColumn('tipo_reclamo_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('descripcion', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('estatus', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('estudiante_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Estudiante', array(
             'local' => 'estudiante_id',
             'foreign' => 'id'));

        $this->hasOne('TipoReclamo', array(
             'local' => 'tipo_reclamo_id',
             'foreign' => 'id'));
    }
}