<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Estudiante', 'doctrine');

/**
 * BaseEstudiante
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $tipo_identificacion
 * @property string $identificacion
 * @property string $primer_nombre
 * @property string $segundo_nombre
 * @property string $primer_apellido
 * @property string $segundo_apellido
 * @property integer $sexo_id
 * @property date $fecha_nacimiento
 * @property integer $pais_origen_id
 * @property integer $estado_id
 * @property integer $municipio_id
 * @property integer $parroquia_id
 * @property string $direccion
 * @property string $punto_referencia
 * @property integer $asic_estado_id
 * @property integer $asic_municipio_id
 * @property integer $asic_id
 * @property decimal $telefono
 * @property decimal $telefono_casa
 * @property string $correo_electronico
 * @property string $persona_contacto
 * @property integer $estado_civil_id
 * @property decimal $n_hijos
 * @property string $ano_curso
 * @property string $cohorte
 * @property integer $etnia_indigena_id
 * @property boolean $elam
 * @property string $idmatricula
 * @property string $trabaja
 * @property string $lugar
 * @property string $horario
 * @property string $ingresos
 * @property decimal $telefono_trabajo
 * @property string $centro_poblado_id
 * @property string $foto
 * @property string $tipo_empresa
 * @property string $estatus
 * @property string $banco
 * @property string $tipo_cuenta
 * @property string $cuenta
 * @property boolean $cta_social
 * @property boolean $cta_personal
 * @property boolean $no_cta
 * @property boolean $n_ingreso
 * @property boolean $opsu
 * @property boolean $postulado
 * @property date $registro
 * @property boolean $verificado
 * @property date $fecha_verificacion
 * @property string $notas
 * @property string $pnf
 * @property integer $codigo_tlf_id
 * @property integer $codigo_tlf_casa_id
 * @property string $parentesco
 * @property integer $codigo_tlf_contacto
 * @property decimal $telefono_contacto
 * @property string $situacion_academica
 * @property string $carnet_patria
 * @property string $serial_carnet_patria
 * @property boolean $afrodescendiente
 * @property boolean $lgbt
 * @property string $dedicacion_laboral
 * @property integer $asic_parroquia_id
 * @property integer $asic_hab_id
 * @property integer $mod_ingreso_id
 * @property Estado $Estado
 * @property Asic $Asic
 * @property Municipio $Municipio
 * @property EstadoCivil $EstadoCivil
 * @property Estado $Estado_5
 * @property EtniaIndigena $EtniaIndigena
 * @property Municipio $Municipio_7
 * @property PaisOrigen $PaisOrigen
 * @property Parroquia $Parroquia
 * @property Sexo $Sexo
 * @property CentroPoblado $CentroPoblado
 * @property CodigoTlf $CodigoTlf
 * @property CodigoTlf $CodigoTlf_13
 * @property CodigoTlf $CodigoTlf_14
 * @property Parroquia $Parroquia_15
 * @property Asic $Asic_16
 * @property ModalidadIngreso $ModalidadIngreso
 * @property Doctrine_Collection $Reclamo
 * @property Doctrine_Collection $Traslado
 * @property Doctrine_Collection $EstudioSocioeconomico
 * @property Doctrine_Collection $Notas
 * @property Doctrine_Collection $OtraInformacion
 * 
 * @method integer             getId()                    Returns the current record's "id" value
 * @method string              getTipoIdentificacion()    Returns the current record's "tipo_identificacion" value
 * @method string              getIdentificacion()        Returns the current record's "identificacion" value
 * @method string              getPrimerNombre()          Returns the current record's "primer_nombre" value
 * @method string              getSegundoNombre()         Returns the current record's "segundo_nombre" value
 * @method string              getPrimerApellido()        Returns the current record's "primer_apellido" value
 * @method string              getSegundoApellido()       Returns the current record's "segundo_apellido" value
 * @method integer             getSexoId()                Returns the current record's "sexo_id" value
 * @method date                getFechaNacimiento()       Returns the current record's "fecha_nacimiento" value
 * @method integer             getPaisOrigenId()          Returns the current record's "pais_origen_id" value
 * @method integer             getEstadoId()              Returns the current record's "estado_id" value
 * @method integer             getMunicipioId()           Returns the current record's "municipio_id" value
 * @method integer             getParroquiaId()           Returns the current record's "parroquia_id" value
 * @method string              getDireccion()             Returns the current record's "direccion" value
 * @method string              getPuntoReferencia()       Returns the current record's "punto_referencia" value
 * @method integer             getAsicEstadoId()          Returns the current record's "asic_estado_id" value
 * @method integer             getAsicMunicipioId()       Returns the current record's "asic_municipio_id" value
 * @method integer             getAsicId()                Returns the current record's "asic_id" value
 * @method decimal             getTelefono()              Returns the current record's "telefono" value
 * @method decimal             getTelefonoCasa()          Returns the current record's "telefono_casa" value
 * @method string              getCorreoElectronico()     Returns the current record's "correo_electronico" value
 * @method string              getPersonaContacto()       Returns the current record's "persona_contacto" value
 * @method integer             getEstadoCivilId()         Returns the current record's "estado_civil_id" value
 * @method decimal             getNHijos()                Returns the current record's "n_hijos" value
 * @method string              getAnoCurso()              Returns the current record's "ano_curso" value
 * @method string              getCohorte()               Returns the current record's "cohorte" value
 * @method integer             getEtniaIndigenaId()       Returns the current record's "etnia_indigena_id" value
 * @method boolean             getElam()                  Returns the current record's "elam" value
 * @method string              getIdmatricula()           Returns the current record's "idmatricula" value
 * @method string              getTrabaja()               Returns the current record's "trabaja" value
 * @method string              getLugar()                 Returns the current record's "lugar" value
 * @method string              getHorario()               Returns the current record's "horario" value
 * @method string              getIngresos()              Returns the current record's "ingresos" value
 * @method decimal             getTelefonoTrabajo()       Returns the current record's "telefono_trabajo" value
 * @method string              getCentroPobladoId()       Returns the current record's "centro_poblado_id" value
 * @method string              getFoto()                  Returns the current record's "foto" value
 * @method string              getTipoEmpresa()           Returns the current record's "tipo_empresa" value
 * @method string              getEstatus()               Returns the current record's "estatus" value
 * @method string              getBanco()                 Returns the current record's "banco" value
 * @method string              getTipoCuenta()            Returns the current record's "tipo_cuenta" value
 * @method string              getCuenta()                Returns the current record's "cuenta" value
 * @method boolean             getCtaSocial()             Returns the current record's "cta_social" value
 * @method boolean             getCtaPersonal()           Returns the current record's "cta_personal" value
 * @method boolean             getNoCta()                 Returns the current record's "no_cta" value
 * @method boolean             getNIngreso()              Returns the current record's "n_ingreso" value
 * @method boolean             getOpsu()                  Returns the current record's "opsu" value
 * @method boolean             getPostulado()             Returns the current record's "postulado" value
 * @method date                getRegistro()              Returns the current record's "registro" value
 * @method boolean             getVerificado()            Returns the current record's "verificado" value
 * @method date                getFechaVerificacion()     Returns the current record's "fecha_verificacion" value
 * @method string              getNotas()                 Returns the current record's "notas" value
 * @method string              getPnf()                   Returns the current record's "pnf" value
 * @method integer             getCodigoTlfId()           Returns the current record's "codigo_tlf_id" value
 * @method integer             getCodigoTlfCasaId()       Returns the current record's "codigo_tlf_casa_id" value
 * @method string              getParentesco()            Returns the current record's "parentesco" value
 * @method integer             getCodigoTlfContacto()     Returns the current record's "codigo_tlf_contacto" value
 * @method decimal             getTelefonoContacto()      Returns the current record's "telefono_contacto" value
 * @method string              getSituacionAcademica()    Returns the current record's "situacion_academica" value
 * @method string              getCarnetPatria()          Returns the current record's "carnet_patria" value
 * @method string              getSerialCarnetPatria()    Returns the current record's "serial_carnet_patria" value
 * @method boolean             getAfrodescendiente()      Returns the current record's "afrodescendiente" value
 * @method boolean             getLgbt()                  Returns the current record's "lgbt" value
 * @method string              getDedicacionLaboral()     Returns the current record's "dedicacion_laboral" value
 * @method integer             getAsicParroquiaId()       Returns the current record's "asic_parroquia_id" value
 * @method integer             getAsicHabId()             Returns the current record's "asic_hab_id" value
 * @method integer             getModIngresoId()          Returns the current record's "mod_ingreso_id" value
 * @method Estado              getEstado()                Returns the current record's "Estado" value
 * @method Asic                getAsic()                  Returns the current record's "Asic" value
 * @method Municipio           getMunicipio()             Returns the current record's "Municipio" value
 * @method EstadoCivil         getEstadoCivil()           Returns the current record's "EstadoCivil" value
 * @method Estado              getEstado5()               Returns the current record's "Estado_5" value
 * @method EtniaIndigena       getEtniaIndigena()         Returns the current record's "EtniaIndigena" value
 * @method Municipio           getMunicipio7()            Returns the current record's "Municipio_7" value
 * @method PaisOrigen          getPaisOrigen()            Returns the current record's "PaisOrigen" value
 * @method Parroquia           getParroquia()             Returns the current record's "Parroquia" value
 * @method Sexo                getSexo()                  Returns the current record's "Sexo" value
 * @method CentroPoblado       getCentroPoblado()         Returns the current record's "CentroPoblado" value
 * @method CodigoTlf           getCodigoTlf()             Returns the current record's "CodigoTlf" value
 * @method CodigoTlf           getCodigoTlf13()           Returns the current record's "CodigoTlf_13" value
 * @method CodigoTlf           getCodigoTlf14()           Returns the current record's "CodigoTlf_14" value
 * @method Parroquia           getParroquia15()           Returns the current record's "Parroquia_15" value
 * @method Asic                getAsic16()                Returns the current record's "Asic_16" value
 * @method ModalidadIngreso    getModalidadIngreso()      Returns the current record's "ModalidadIngreso" value
 * @method Doctrine_Collection getReclamo()               Returns the current record's "Reclamo" collection
 * @method Doctrine_Collection getTraslado()              Returns the current record's "Traslado" collection
 * @method Doctrine_Collection getEstudioSocioeconomico() Returns the current record's "EstudioSocioeconomico" collection
 * @method Doctrine_Collection getNotas()                 Returns the current record's "Notas" collection
 * @method Doctrine_Collection getOtraInformacion()       Returns the current record's "OtraInformacion" collection
 * @method Estudiante          setId()                    Sets the current record's "id" value
 * @method Estudiante          setTipoIdentificacion()    Sets the current record's "tipo_identificacion" value
 * @method Estudiante          setIdentificacion()        Sets the current record's "identificacion" value
 * @method Estudiante          setPrimerNombre()          Sets the current record's "primer_nombre" value
 * @method Estudiante          setSegundoNombre()         Sets the current record's "segundo_nombre" value
 * @method Estudiante          setPrimerApellido()        Sets the current record's "primer_apellido" value
 * @method Estudiante          setSegundoApellido()       Sets the current record's "segundo_apellido" value
 * @method Estudiante          setSexoId()                Sets the current record's "sexo_id" value
 * @method Estudiante          setFechaNacimiento()       Sets the current record's "fecha_nacimiento" value
 * @method Estudiante          setPaisOrigenId()          Sets the current record's "pais_origen_id" value
 * @method Estudiante          setEstadoId()              Sets the current record's "estado_id" value
 * @method Estudiante          setMunicipioId()           Sets the current record's "municipio_id" value
 * @method Estudiante          setParroquiaId()           Sets the current record's "parroquia_id" value
 * @method Estudiante          setDireccion()             Sets the current record's "direccion" value
 * @method Estudiante          setPuntoReferencia()       Sets the current record's "punto_referencia" value
 * @method Estudiante          setAsicEstadoId()          Sets the current record's "asic_estado_id" value
 * @method Estudiante          setAsicMunicipioId()       Sets the current record's "asic_municipio_id" value
 * @method Estudiante          setAsicId()                Sets the current record's "asic_id" value
 * @method Estudiante          setTelefono()              Sets the current record's "telefono" value
 * @method Estudiante          setTelefonoCasa()          Sets the current record's "telefono_casa" value
 * @method Estudiante          setCorreoElectronico()     Sets the current record's "correo_electronico" value
 * @method Estudiante          setPersonaContacto()       Sets the current record's "persona_contacto" value
 * @method Estudiante          setEstadoCivilId()         Sets the current record's "estado_civil_id" value
 * @method Estudiante          setNHijos()                Sets the current record's "n_hijos" value
 * @method Estudiante          setAnoCurso()              Sets the current record's "ano_curso" value
 * @method Estudiante          setCohorte()               Sets the current record's "cohorte" value
 * @method Estudiante          setEtniaIndigenaId()       Sets the current record's "etnia_indigena_id" value
 * @method Estudiante          setElam()                  Sets the current record's "elam" value
 * @method Estudiante          setIdmatricula()           Sets the current record's "idmatricula" value
 * @method Estudiante          setTrabaja()               Sets the current record's "trabaja" value
 * @method Estudiante          setLugar()                 Sets the current record's "lugar" value
 * @method Estudiante          setHorario()               Sets the current record's "horario" value
 * @method Estudiante          setIngresos()              Sets the current record's "ingresos" value
 * @method Estudiante          setTelefonoTrabajo()       Sets the current record's "telefono_trabajo" value
 * @method Estudiante          setCentroPobladoId()       Sets the current record's "centro_poblado_id" value
 * @method Estudiante          setFoto()                  Sets the current record's "foto" value
 * @method Estudiante          setTipoEmpresa()           Sets the current record's "tipo_empresa" value
 * @method Estudiante          setEstatus()               Sets the current record's "estatus" value
 * @method Estudiante          setBanco()                 Sets the current record's "banco" value
 * @method Estudiante          setTipoCuenta()            Sets the current record's "tipo_cuenta" value
 * @method Estudiante          setCuenta()                Sets the current record's "cuenta" value
 * @method Estudiante          setCtaSocial()             Sets the current record's "cta_social" value
 * @method Estudiante          setCtaPersonal()           Sets the current record's "cta_personal" value
 * @method Estudiante          setNoCta()                 Sets the current record's "no_cta" value
 * @method Estudiante          setNIngreso()              Sets the current record's "n_ingreso" value
 * @method Estudiante          setOpsu()                  Sets the current record's "opsu" value
 * @method Estudiante          setPostulado()             Sets the current record's "postulado" value
 * @method Estudiante          setRegistro()              Sets the current record's "registro" value
 * @method Estudiante          setVerificado()            Sets the current record's "verificado" value
 * @method Estudiante          setFechaVerificacion()     Sets the current record's "fecha_verificacion" value
 * @method Estudiante          setNotas()                 Sets the current record's "notas" value
 * @method Estudiante          setPnf()                   Sets the current record's "pnf" value
 * @method Estudiante          setCodigoTlfId()           Sets the current record's "codigo_tlf_id" value
 * @method Estudiante          setCodigoTlfCasaId()       Sets the current record's "codigo_tlf_casa_id" value
 * @method Estudiante          setParentesco()            Sets the current record's "parentesco" value
 * @method Estudiante          setCodigoTlfContacto()     Sets the current record's "codigo_tlf_contacto" value
 * @method Estudiante          setTelefonoContacto()      Sets the current record's "telefono_contacto" value
 * @method Estudiante          setSituacionAcademica()    Sets the current record's "situacion_academica" value
 * @method Estudiante          setCarnetPatria()          Sets the current record's "carnet_patria" value
 * @method Estudiante          setSerialCarnetPatria()    Sets the current record's "serial_carnet_patria" value
 * @method Estudiante          setAfrodescendiente()      Sets the current record's "afrodescendiente" value
 * @method Estudiante          setLgbt()                  Sets the current record's "lgbt" value
 * @method Estudiante          setDedicacionLaboral()     Sets the current record's "dedicacion_laboral" value
 * @method Estudiante          setAsicParroquiaId()       Sets the current record's "asic_parroquia_id" value
 * @method Estudiante          setAsicHabId()             Sets the current record's "asic_hab_id" value
 * @method Estudiante          setModIngresoId()          Sets the current record's "mod_ingreso_id" value
 * @method Estudiante          setEstado()                Sets the current record's "Estado" value
 * @method Estudiante          setAsic()                  Sets the current record's "Asic" value
 * @method Estudiante          setMunicipio()             Sets the current record's "Municipio" value
 * @method Estudiante          setEstadoCivil()           Sets the current record's "EstadoCivil" value
 * @method Estudiante          setEstado5()               Sets the current record's "Estado_5" value
 * @method Estudiante          setEtniaIndigena()         Sets the current record's "EtniaIndigena" value
 * @method Estudiante          setMunicipio7()            Sets the current record's "Municipio_7" value
 * @method Estudiante          setPaisOrigen()            Sets the current record's "PaisOrigen" value
 * @method Estudiante          setParroquia()             Sets the current record's "Parroquia" value
 * @method Estudiante          setSexo()                  Sets the current record's "Sexo" value
 * @method Estudiante          setCentroPoblado()         Sets the current record's "CentroPoblado" value
 * @method Estudiante          setCodigoTlf()             Sets the current record's "CodigoTlf" value
 * @method Estudiante          setCodigoTlf13()           Sets the current record's "CodigoTlf_13" value
 * @method Estudiante          setCodigoTlf14()           Sets the current record's "CodigoTlf_14" value
 * @method Estudiante          setParroquia15()           Sets the current record's "Parroquia_15" value
 * @method Estudiante          setAsic16()                Sets the current record's "Asic_16" value
 * @method Estudiante          setModalidadIngreso()      Sets the current record's "ModalidadIngreso" value
 * @method Estudiante          setReclamo()               Sets the current record's "Reclamo" collection
 * @method Estudiante          setTraslado()              Sets the current record's "Traslado" collection
 * @method Estudiante          setEstudioSocioeconomico() Sets the current record's "EstudioSocioeconomico" collection
 * @method Estudiante          setNotas()                 Sets the current record's "Notas" collection
 * @method Estudiante          setOtraInformacion()       Sets the current record's "OtraInformacion" collection
 * 
 * @package    ucs_control
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEstudiante extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('estudiante');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'estudiante_id',
             'length' => 4,
             ));
        $this->hasColumn('tipo_identificacion', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('identificacion', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('primer_nombre', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('segundo_nombre', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('primer_apellido', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('segundo_apellido', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('sexo_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('fecha_nacimiento', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 25,
             ));
        $this->hasColumn('pais_origen_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('estado_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('municipio_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('parroquia_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('direccion', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('punto_referencia', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('asic_estado_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('asic_municipio_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('asic_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('telefono', 'decimal', 18, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 18,
             ));
        $this->hasColumn('telefono_casa', 'decimal', 18, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 18,
             ));
        $this->hasColumn('correo_electronico', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('persona_contacto', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('estado_civil_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('n_hijos', 'decimal', 18, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 18,
             ));
        $this->hasColumn('ano_curso', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('cohorte', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('etnia_indigena_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('elam', 'boolean', 1, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('idmatricula', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('trabaja', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('lugar', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('horario', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('ingresos', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('telefono_trabajo', 'decimal', 18, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 18,
             ));
        $this->hasColumn('centro_poblado_id', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('foto', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('tipo_empresa', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('estatus', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('banco', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('tipo_cuenta', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('cuenta', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('cta_social', 'boolean', 1, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('cta_personal', 'boolean', 1, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('no_cta', 'boolean', 1, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('n_ingreso', 'boolean', 1, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('opsu', 'boolean', 1, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('postulado', 'boolean', 1, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('registro', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 25,
             ));
        $this->hasColumn('verificado', 'boolean', 1, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('fecha_verificacion', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 25,
             ));
        $this->hasColumn('notas', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('pnf', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('codigo_tlf_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('codigo_tlf_casa_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('parentesco', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('codigo_tlf_contacto', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('telefono_contacto', 'decimal', 18, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 18,
             ));
        $this->hasColumn('situacion_academica', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('carnet_patria', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('serial_carnet_patria', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('afrodescendiente', 'boolean', 1, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('lgbt', 'boolean', 1, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('dedicacion_laboral', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('asic_parroquia_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('asic_hab_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('mod_ingreso_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Estado', array(
             'local' => 'asic_estado_id',
             'foreign' => 'id'));

        $this->hasOne('Asic', array(
             'local' => 'asic_id',
             'foreign' => 'id'));

        $this->hasOne('Municipio', array(
             'local' => 'asic_municipio_id',
             'foreign' => 'id'));

        $this->hasOne('EstadoCivil', array(
             'local' => 'estado_civil_id',
             'foreign' => 'id'));

        $this->hasOne('Estado as Estado_5', array(
             'local' => 'estado_id',
             'foreign' => 'id'));

        $this->hasOne('EtniaIndigena', array(
             'local' => 'etnia_indigena_id',
             'foreign' => 'id'));

        $this->hasOne('Municipio as Municipio_7', array(
             'local' => 'municipio_id',
             'foreign' => 'id'));

        $this->hasOne('PaisOrigen', array(
             'local' => 'pais_origen_id',
             'foreign' => 'id'));

        $this->hasOne('Parroquia', array(
             'local' => 'parroquia_id',
             'foreign' => 'id'));

        $this->hasOne('Sexo', array(
             'local' => 'sexo_id',
             'foreign' => 'id'));

        $this->hasOne('CentroPoblado', array(
             'local' => 'centro_poblado_id',
             'foreign' => 'id'));

        $this->hasOne('CodigoTlf', array(
             'local' => 'codigo_tlf_id',
             'foreign' => 'id'));

        $this->hasOne('CodigoTlf as CodigoTlf_13', array(
             'local' => 'codigo_tlf_casa_id',
             'foreign' => 'id'));

        $this->hasOne('CodigoTlf as CodigoTlf_14', array(
             'local' => 'codigo_tlf_contacto',
             'foreign' => 'id'));

        $this->hasOne('Parroquia as Parroquia_15', array(
             'local' => 'asic_parroquia_id',
             'foreign' => 'id'));

        $this->hasOne('Asic as Asic_16', array(
             'local' => 'asic_hab_id',
             'foreign' => 'id'));

        $this->hasOne('ModalidadIngreso', array(
             'local' => 'mod_ingreso_id',
             'foreign' => 'id'));

        $this->hasMany('Reclamo', array(
             'local' => 'id',
             'foreign' => 'estudiante_id'));

        $this->hasMany('Traslado', array(
             'local' => 'id',
             'foreign' => 'estudiante_id'));

        $this->hasMany('EstudioSocioeconomico', array(
             'local' => 'id',
             'foreign' => 'estudiante_id'));

        $this->hasMany('Notas', array(
             'local' => 'id',
             'foreign' => 'estudiante_id'));

        $this->hasMany('OtraInformacion', array(
             'local' => 'id',
             'foreign' => 'estudiante_id'));
    }
}