<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Estado', 'doctrine');

/**
 * BaseEstado
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $descripcion
 * @property Doctrine_Collection $Estudiante
 * @property Doctrine_Collection $Estudiante_5
 * 
 * @method integer             getId()           Returns the current record's "id" value
 * @method string              getDescripcion()  Returns the current record's "descripcion" value
 * @method Doctrine_Collection getEstudiante()   Returns the current record's "Estudiante" collection
 * @method Doctrine_Collection getEstudiante5()  Returns the current record's "Estudiante_5" collection
 * @method Estado              setId()           Sets the current record's "id" value
 * @method Estado              setDescripcion()  Sets the current record's "descripcion" value
 * @method Estado              setEstudiante()   Sets the current record's "Estudiante" collection
 * @method Estado              setEstudiante5()  Sets the current record's "Estudiante_5" collection
 * 
 * @package    ucs_control
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEstado extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('estado');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'estado_id',
             'length' => 4,
             ));
        $this->hasColumn('descripcion', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Estudiante', array(
             'local' => 'id',
             'foreign' => 'asic_estado_id'));

        $this->hasMany('Estudiante as Estudiante_5', array(
             'local' => 'id',
             'foreign' => 'estado_id'));
    }
}