<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Usuario', 'doctrine');

/**
 * BaseUsuario
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $persona_id
 * @property string $usuario_nom
 * @property string $usuario_cla
 * @property integer $usutip_id
 * @property integer $usuper_id
 * @property string $usuario_pr1
 * @property string $usuario_re1
 * @property string $usuario_pr2
 * @property string $usuario_re2
 * @property date $usuario_fre
 * @property date $usuario_fbl
 * @property date $usuario_fde
 * @property string $usuario_obs
 * @property integer $ususes_id
 * @property integer $usuest_id
 * @property integer $usurdi_id
 * 
 * @method integer getId()          Returns the current record's "id" value
 * @method integer getPersonaId()   Returns the current record's "persona_id" value
 * @method string  getUsuarioNom()  Returns the current record's "usuario_nom" value
 * @method string  getUsuarioCla()  Returns the current record's "usuario_cla" value
 * @method integer getUsutipId()    Returns the current record's "usutip_id" value
 * @method integer getUsuperId()    Returns the current record's "usuper_id" value
 * @method string  getUsuarioPr1()  Returns the current record's "usuario_pr1" value
 * @method string  getUsuarioRe1()  Returns the current record's "usuario_re1" value
 * @method string  getUsuarioPr2()  Returns the current record's "usuario_pr2" value
 * @method string  getUsuarioRe2()  Returns the current record's "usuario_re2" value
 * @method date    getUsuarioFre()  Returns the current record's "usuario_fre" value
 * @method date    getUsuarioFbl()  Returns the current record's "usuario_fbl" value
 * @method date    getUsuarioFde()  Returns the current record's "usuario_fde" value
 * @method string  getUsuarioObs()  Returns the current record's "usuario_obs" value
 * @method integer getUsusesId()    Returns the current record's "ususes_id" value
 * @method integer getUsuestId()    Returns the current record's "usuest_id" value
 * @method integer getUsurdiId()    Returns the current record's "usurdi_id" value
 * @method Usuario setId()          Sets the current record's "id" value
 * @method Usuario setPersonaId()   Sets the current record's "persona_id" value
 * @method Usuario setUsuarioNom()  Sets the current record's "usuario_nom" value
 * @method Usuario setUsuarioCla()  Sets the current record's "usuario_cla" value
 * @method Usuario setUsutipId()    Sets the current record's "usutip_id" value
 * @method Usuario setUsuperId()    Sets the current record's "usuper_id" value
 * @method Usuario setUsuarioPr1()  Sets the current record's "usuario_pr1" value
 * @method Usuario setUsuarioRe1()  Sets the current record's "usuario_re1" value
 * @method Usuario setUsuarioPr2()  Sets the current record's "usuario_pr2" value
 * @method Usuario setUsuarioRe2()  Sets the current record's "usuario_re2" value
 * @method Usuario setUsuarioFre()  Sets the current record's "usuario_fre" value
 * @method Usuario setUsuarioFbl()  Sets the current record's "usuario_fbl" value
 * @method Usuario setUsuarioFde()  Sets the current record's "usuario_fde" value
 * @method Usuario setUsuarioObs()  Sets the current record's "usuario_obs" value
 * @method Usuario setUsusesId()    Sets the current record's "ususes_id" value
 * @method Usuario setUsuestId()    Sets the current record's "usuest_id" value
 * @method Usuario setUsurdiId()    Sets the current record's "usurdi_id" value
 * 
 * @package    ucs_control
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUsuario extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('usuario');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'usuario_id',
             'length' => 4,
             ));
        $this->hasColumn('persona_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('usuario_nom', 'string', 9, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 9,
             ));
        $this->hasColumn('usuario_cla', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('usutip_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('usuper_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('usuario_pr1', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('usuario_re1', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('usuario_pr2', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('usuario_re2', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('usuario_fre', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 25,
             ));
        $this->hasColumn('usuario_fbl', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 25,
             ));
        $this->hasColumn('usuario_fde', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 25,
             ));
        $this->hasColumn('usuario_obs', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('ususes_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('usuest_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('usurdi_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}