<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Pnf', 'doctrine');

/**
 * BasePnf
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $codigo
 * @property string $descripcion
 * @property Doctrine_Collection $UnidadCurricular
 * @property Doctrine_Collection $Notas
 * 
 * @method integer             getId()               Returns the current record's "id" value
 * @method string              getCodigo()           Returns the current record's "codigo" value
 * @method string              getDescripcion()      Returns the current record's "descripcion" value
 * @method Doctrine_Collection getUnidadCurricular() Returns the current record's "UnidadCurricular" collection
 * @method Doctrine_Collection getNotas()            Returns the current record's "Notas" collection
 * @method Pnf                 setId()               Sets the current record's "id" value
 * @method Pnf                 setCodigo()           Sets the current record's "codigo" value
 * @method Pnf                 setDescripcion()      Sets the current record's "descripcion" value
 * @method Pnf                 setUnidadCurricular() Sets the current record's "UnidadCurricular" collection
 * @method Pnf                 setNotas()            Sets the current record's "Notas" collection
 * 
 * @package    ucs_control
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePnf extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('pnf');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'pnf_id',
             'length' => 4,
             ));
        $this->hasColumn('codigo', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('descripcion', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('UnidadCurricular', array(
             'local' => 'id',
             'foreign' => 'pnf_id'));

        $this->hasMany('Notas', array(
             'local' => 'id',
             'foreign' => 'pnf_id'));
    }
}