<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('UnidadCurricular', 'doctrine');

/**
 * BaseUnidadCurricular
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $mmc_id
 * @property string $descripcion
 * @property integer $pnf_id
 * @property string $cod_unerg
 * @property string $ano_acad
 * @property string $cod_sec_nac
 * @property string $cod_ubv
 * @property integer $asig_ig
 * @property string $periodo_old
 * @property string $periodo_sec
 * @property string $periodo_un
 * @property string $prelacion
 * @property string $periodo_id
 * @property string $trayecto_id
 * @property Pnf $Pnf
 * @property Doctrine_Collection $Notas
 * 
 * @method integer             getId()          Returns the current record's "id" value
 * @method integer             getMmcId()       Returns the current record's "mmc_id" value
 * @method string              getDescripcion() Returns the current record's "descripcion" value
 * @method integer             getPnfId()       Returns the current record's "pnf_id" value
 * @method string              getCodUnerg()    Returns the current record's "cod_unerg" value
 * @method string              getAnoAcad()     Returns the current record's "ano_acad" value
 * @method string              getCodSecNac()   Returns the current record's "cod_sec_nac" value
 * @method string              getCodUbv()      Returns the current record's "cod_ubv" value
 * @method integer             getAsigIg()      Returns the current record's "asig_ig" value
 * @method string              getPeriodoOld()  Returns the current record's "periodo_old" value
 * @method string              getPeriodoSec()  Returns the current record's "periodo_sec" value
 * @method string              getPeriodoUn()   Returns the current record's "periodo_un" value
 * @method string              getPrelacion()   Returns the current record's "prelacion" value
 * @method string              getPeriodoId()   Returns the current record's "periodo_id" value
 * @method string              getTrayectoId()  Returns the current record's "trayecto_id" value
 * @method Pnf                 getPnf()         Returns the current record's "Pnf" value
 * @method Doctrine_Collection getNotas()       Returns the current record's "Notas" collection
 * @method UnidadCurricular    setId()          Sets the current record's "id" value
 * @method UnidadCurricular    setMmcId()       Sets the current record's "mmc_id" value
 * @method UnidadCurricular    setDescripcion() Sets the current record's "descripcion" value
 * @method UnidadCurricular    setPnfId()       Sets the current record's "pnf_id" value
 * @method UnidadCurricular    setCodUnerg()    Sets the current record's "cod_unerg" value
 * @method UnidadCurricular    setAnoAcad()     Sets the current record's "ano_acad" value
 * @method UnidadCurricular    setCodSecNac()   Sets the current record's "cod_sec_nac" value
 * @method UnidadCurricular    setCodUbv()      Sets the current record's "cod_ubv" value
 * @method UnidadCurricular    setAsigIg()      Sets the current record's "asig_ig" value
 * @method UnidadCurricular    setPeriodoOld()  Sets the current record's "periodo_old" value
 * @method UnidadCurricular    setPeriodoSec()  Sets the current record's "periodo_sec" value
 * @method UnidadCurricular    setPeriodoUn()   Sets the current record's "periodo_un" value
 * @method UnidadCurricular    setPrelacion()   Sets the current record's "prelacion" value
 * @method UnidadCurricular    setPeriodoId()   Sets the current record's "periodo_id" value
 * @method UnidadCurricular    setTrayectoId()  Sets the current record's "trayecto_id" value
 * @method UnidadCurricular    setPnf()         Sets the current record's "Pnf" value
 * @method UnidadCurricular    setNotas()       Sets the current record's "Notas" collection
 * 
 * @package    ucs_control
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUnidadCurricular extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('unidad_curricular');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'unidad_curricular_id',
             'length' => 4,
             ));
        $this->hasColumn('mmc_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('descripcion', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('pnf_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('cod_unerg', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('ano_acad', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('cod_sec_nac', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('cod_ubv', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('asig_ig', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('periodo_old', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('periodo_sec', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('periodo_un', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('prelacion', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('periodo_id', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('trayecto_id', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Pnf', array(
             'local' => 'pnf_id',
             'foreign' => 'id'));

        $this->hasMany('Notas', array(
             'local' => 'id',
             'foreign' => 'unidad_curricular_id'));
    }
}