<?php

/**
 * AsicTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AsicTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AsicTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Asic');
    }
}