<?php

/**
 * CentroPobladoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CentroPobladoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CentroPobladoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CentroPoblado');
    }
}