<?php

/**
 * CodigoTlfTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CodigoTlfTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CodigoTlfTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CodigoTlf');
    }
}