<?php

/**
 * CondicionViviendaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CondicionViviendaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CondicionViviendaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CondicionVivienda');
    }
}