<?php

/**
 * EstudioSocioeconomicoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EstudioSocioeconomicoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EstudioSocioeconomicoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EstudioSocioeconomico');
    }
}