<?php

/**
 * EtniaIndigenaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EtniaIndigenaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EtniaIndigenaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EtniaIndigena');
    }
}