<?php

/**
 * GrupoFamiliarTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GrupoFamiliarTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GrupoFamiliarTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GrupoFamiliar');
    }
}