<?php

/**
 * IngresoFamiliarTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IngresoFamiliarTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object IngresoFamiliarTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('IngresoFamiliar');
    }
}