<?php

/**
 * InstruccionMadreTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class InstruccionMadreTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object InstruccionMadreTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('InstruccionMadre');
    }
}