<?php

/**
 * MaterialParedesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MaterialParedesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MaterialParedesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MaterialParedes');
    }
}