<?php

/**
 * MaterialPisoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MaterialPisoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MaterialPisoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MaterialPiso');
    }
}