<?php

/**
 * MaterialTechoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MaterialTechoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MaterialTechoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MaterialTecho');
    }
}