<?php

/**
 * OtraInformacionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OtraInformacionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OtraInformacionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OtraInformacion');
    }
        public static function buscarOtra($id)
    {
        $sql="select * from otra_informacion where estudiante_id=$id";
        $q=Doctrine_Manager::getInstance()->getCurrentConnection()->fetchAssoc($sql);
        return $q;
    }
}