<?php

/**
 * PaisOrigenTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PaisOrigenTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PaisOrigenTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PaisOrigen');
    }
}