<?php

/**
 * ParroquiaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ParroquiaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ParroquiaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Parroquia');
    }
}