<?php

/**
 * PeriodoLectivoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PeriodoLectivoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PeriodoLectivoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PeriodoLectivo');
    }
}