<?php

/**
 * PnfTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PnfTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PnfTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Pnf');
    }
}