<?php

/**
 * PreinscripcionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PreinscripcionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PreinscripcionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Preinscripcion');
    }
}