<?php

/**
 * ProfesionJefeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProfesionJefeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProfesionJefeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProfesionJefe');
    }
}