<?php

/**
 * Reclamo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ucs_control
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Reclamo extends BaseReclamo
{
    public function save(Doctrine_Connection $conn = null){
        if (sfConfig::get("sf_app") == 'estudiante') {
             $this->setEstatus('REGISTRADO');
             $this->setEstudianteId(sfContext::getInstance()->getUser()->getAttribute('estudiante_id'));
        }
        return parent::save($conn);
    }
}