<?php

/**
 * ReclamoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ReclamoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ReclamoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Reclamo');
    }
        public function obtenerReclamo() {
        $id=sfContext::getInstance()->getUser()->getAttribute('estudiante_id');
        $q = Doctrine_Query::create()
                ->from('reclamo r')
                ->addWhere('estudiante_id=?', $id);
        return $q;
    }
}