<?php

/**
 * RezagadosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RezagadosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RezagadosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Rezagados');
    }
}