<?php

/**
 * Rezagados2Table
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Rezagados2Table extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Rezagados2Table
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Rezagados2');
    }
}