<?php

/**
 * SexoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SexoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SexoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Sexo');
    }
}