<?php

/**
 * TenenciaViviendaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TenenciaViviendaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TenenciaViviendaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TenenciaVivienda');
    }
}