<?php

/**
 * TipoReclamoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TipoReclamoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TipoReclamoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TipoReclamo');
    }
}