<?php

/**
 * TituloTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TituloTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TituloTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Titulo');
    }
}