<?php

/**
 * TrasladoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TrasladoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TrasladoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Traslado');
    }
    public function obtenerTraslado() {
        $id = sfContext::getInstance()->getUser()->getAttribute('estudiante_id');
        $q = Doctrine_Query::create()
                ->from('traslado t')
                ->addWhere('estudiante_id=?', $id);
        return $q;
    }
}