<?php

/**
 * UnidadCurricularTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UnidadCurricularTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UnidadCurricularTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UnidadCurricular');
    }
        public function getUi() {
        $id = sfContext::getInstance()->getUser()->getAttribute('estudiante_id');
        $q = Doctrine_Query::create()
                ->from('UnidadCurricular u')
                ->addWhere("u.id not in (select unidad_curricular_id from notas where estudiante_id='$id')")
                ->addOrderBy('id', 'ASC');
        return $q;
    }
}