<?php

/**
 * UsuarioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UsuarioTable extends Doctrine_Table{
    /**
     * Returns an instance of this class.
     *
     * @return object UsuarioTable
     */

    public static function getInstance(){
        return Doctrine_Core::getTable('usuario');
    }
/*------------------------- FUNCION FORM = BUSCARUSUARIO(RCL)-BUSCAR(REGISTRAR)  -------------------------*/
    public static function buscaRegistro($persona_id){
        $sql="SELECT *
              FROM usuario
              WHERE persona_id='$persona_id'";
        $q=Doctrine_Manager::getInstance()->getCurrentConnection()->fetchAssoc($sql);
        return $q;
    }
/*------------------------- FUNCION FORM = LOGIN-BUSCAR(REGISTRAR)  -------------------------*/
    public static function buscaUsuario($usuario_nom){
        $sql="SELECT *
              FROM usuario
              WHERE usuario_nom = '$usuario_nom'";
        $q=Doctrine_Manager::getInstance()->getCurrentConnection()->fetchAssoc($sql);
        return $q;
    }
/*------------------------- FUNCION FORM = RECUPERA  -------------------------*/
    public static function actualizaClave($usuario_id, $clave){
        $opciones = ['cost' => 12,];
        $usuario_cla = password_hash($clave, PASSWORD_BCRYPT, $opciones);
            $sql="UPDATE usuario
                  SET usuario_cla = '".$usuario_cla."'
                  WHERE id = $usuario_id";
        $q=Doctrine_Manager::getInstance()->getCurrentConnection()->fetchAssoc($sql);
        return $q;
    }
    public static function usuario1Vez($id){
        $sql="update usuario set usurdi_id=1 where persona_id='$id'";
        $q=Doctrine_Manager::getInstance()->getCurrentConnection()->fetchAssoc($sql);
        return $q;
    }
    public function obtenerUsuario(){
        $id=sfContext::getInstance()->getUser()->getAttribute('estudiante_id');
        if($id!=''){
        $q = Doctrine_Query::create()
                ->from('usuario u')
        ->addWhere('persona_id=?', $id);
        }else{
            $q = Doctrine_Query::create()
                ->from('usuario u');
        }
        return $q;
    }
    
}
