<?php

/**
 * Usuario
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ucs_control
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Usuario extends BaseUsuario {

    public function save(Doctrine_Connection $conn = null) {
        // $this->setContrasena(crypt($this->getContrasena(), 'S1g3'));
        $opciones = ['cost' => 12,];
        $usuario_cla = password_hash($this->getUsuarioCla(), PASSWORD_BCRYPT, $opciones);
        $this->setUsuarioCla($usuario_cla);
//        if (sfConfig::get("sf_app") == 'frontend') {
            $this->setUsutipId('1');
            $this->setUsuarioFre(date("Y/m/d"));
            $this->setUsusesId('2');
            $this->setUsuestId('1');
            $this->setUsurdiId('2');
//        }
        $this->setPersonaId(sfContext::getInstance()->getUser()->getAttribute('estudiante_id'));
        return parent::save($conn);
    }

}
