generator:
  class: sfDoctrineGenerator
  param:
    model_class:           reclamo
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          reclamo
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    
          title: Reclamos
          table_method: obtenerReclamo
          display: [tipo_reclamo,descripcion,estatus]

      filter:  
          class: false
      form:    ~
  
      edit:    
          title: Reclamos
      new:     
          title: Reclamos
          
